/*
 * This source file was generated by the Gradle 'init' task
 */
package expensetracker;

import main.java.expensetracker.AppUI;

public class App {
    public String getGreeting() {
        return "Hello World!";
        
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        AppUI appUI = new AppUI();
        appUI.runUI();
    }
}
